### ISSUE TITLE
Ram Usage

### ISSUE THREAD

**Issue by shubhamkr2242** [rishianand54/devanagari-character-recognition-system#1]
Hi
Running the "Extract Images into a Dataset" part uses up my entire 8gb ram and my pc freezes.
Is there any workaround to this.

**Comment by rishianand54** [comment]
Where does the problem occur? Is it while reading the images and writing to the csv file, or reading the csv file? If your problem is from reading the complete csv file, you could instead read a random sample of the data.
This should be the correct solution https://stackoverflow.com/a/48589768

**Comment by shubhamkr2242** [comment]
I think the problem is due to the code trying to first read all images into RAM and then process them, instead of reading one image and processing it and continue doing like that.
Problem occurs while reading the image and writing the csv file before output "=".

**Comment by rishianand54** [comment]
Does the code output at least one "=", or does the system freeze before that?

In the code, all images of one character is read at once into the memory — before writing it to the csv file. But that definitely should not eat up 8 GiB of memory.
An img_df variable should take up memory = (8 bit per value)  * (256 values per image) * (2000 images per character)
= 500 KiB per character

Anyway, reading the images one at a time would take way too much time. But you can definitely try to split up the process into sub-processes.

**Comment by shubhamkr2242** [comment]
This Helped

https://stackoverflow.com/questions/55290125/wrong-code-logic-for-processing-large-number-of-files?noredirect=1#comment97338789_55290125
